name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ImNikdo/projekt
      - run: |
          git config --global user.email "burianek.jan@protonmail.com"
          git config --global user.name "satanicantichrist"
          git push prod
